DROP TABLE IF EXISTS CARPART;
DROP TABLE IF EXISTS CAR;

CREATE TABLE CAR (
  ID int(11) NOT NULL AUTO_INCREMENT,
  BRAND varchar(200) NOT NULL,
  MODEL varchar(200) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CARPART (
  ID int(11) NOT NULL AUTO_INCREMENT,
  CAR_ID int(11) NOT NULL,
  NAME varchar(200) NOT NULL,
  PRICE decimal(10,2)  NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (CAR_ID) REFERENCES CAR(ID)
);